openapi: 3.0.0
info:
  title: Scorekeeper API
  description: API for managing game history
  version: 1.0.0

servers:
  - url: https://localhost:8080
    description: Local
  - url: https://scorek-score-givbsinrjlo6-310725690.us-west-2.elb.amazonaws.com/
    description: Remote

security:
  - bearerAuth: []

tags:
  - name: Games
    description: Game management operations
  - name: Guesses
    description: Guess submission and grading

paths:
  /game/{game_id}:
    $ref: './paths/games.yaml#/game-get'
  /game:
    $ref: './paths/games.yaml#/game-post'
  /guess:
    $ref: './paths/guess.yaml#/guess-put'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

  schemas:
    $ref: './components/schemas/_index.yaml'
