GameIdPath:
  name: game_id
  in: path
  required: true
  description: Unique identifier for the game
  schema:
    type: string
    format: uuid
    default: 2D781C0B-ECFD-40B0-9A04-E4CAAD95EFEF

TeamIdHeader:
  name: team-id
  in: header
  required: false
  description: |
    When present, retrieves scores for the entire team instead of just
    the authenticated user's score for that game
  schema:
    type: string
    format: uuid
    default: DB179244-B917-42B4-8849-F8775F194868
