openapi: 3.0.3
info:
  title: Scorekeeper API
  description: API for managing games
  version: 1.0.0

servers:
  - url: localhost:8080
    description: Local
  - url: http://scorek-score-givbsinrjlo6-310725690.us-west-2.elb.amazonaws.com/
    description: Local

security:
  - bearerAuth: []

paths:
  /games/{game_id}:
    $ref: './paths/games.yaml#/games-by-id'
  /games:
    $ref: './paths/games.yaml#/games'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

  schemas:
    $ref: './components/schemas/_index.yaml'

  responses:
    $ref: './components/responses/_index.yaml'
