// AGENTS: DO NOT EDIT THIS FILE WITHOUT EXPLICIT, EXTRA PERMISSION

// # Data Model

// ## API Requests

// Gameplay

// ### PUT:guess/

// Request Body: Game
interface Game { // pls use GameUngraded instead
    puzzle_date_iso_day: string;
    moves: string[];          // 1-6 items, each string is alphanumeric and 5 letters long
}

interface GameUngraded { // pls rename GameUngraded
    puzzle_date_iso_day: string;
    movesUngraded: string[];          // 1-6 items, each string is alphanumeric and 5 letters long
}

// Front End only??
interface GameGraded {
    puzzle_date_iso_day: string
    movesGraded: GuessGraded[]
}


// Response Body: GameGraded
type LetterGrade = 'correct' | 'contained' | 'wrong';

interface GuessLetterGraded {
    letter: string;           // string length == 1
    grade: LetterGrade;
}
type GuessGraded = [
    GuessLetterGraded,
    GuessLetterGraded,
    GuessLetterGraded,
    GuessLetterGraded,
    GuessLetterGraded,
];

interface GameMetadata {
    game_id: string
    user_id: string
    moves_qty: number
    won: boolean,
}

interface GameGraded extends GameMetadata {
    moves: [                 // 1-6 items
        GuessGraded,
        GuessGraded?,
        GuessGraded?,
        GuessGraded?,
        GuessGraded?,
        GuessGraded?,
    ];
}

interface Score extends GameMetadata {
    score: string[]         // 1-6 5-char strings. The emojis that represent the graded game
}

// ### GET:score             // get a user's scores
//      request params:
//         - user_id?: string        // if not provided, inferred from auth
//         - puzzle_date_iso_day?: string
//         - start_dt_millis?: number
//         - end_dt_millis?: number
//     Response:
//         body: Score[]

// Profile
// ### GET:profile.          // a user's full profile

interface UserProfilePreview {
    user_id: string
    display_name: string
    name_pronunciation_url?: string
    pronouns?: string
    avatarUrl?: string
}

// Response Body: UserProfile
interface UserProfile extends UserProfilePreview {
    full_name?: string
    team_ids: string[]
    email: string
    city?: string
    state?: string
    country?: string
}

// Team

type TeamRole = 'admin' | 'member'

// ### PUT:team/teammate    // add a teammate
// ### DELETE:team/teammate // remove a teammate
// request body
interface TeamMembership {
    team_id: string
    user_id: string
    role: TeamRole
}

// request response: Teammate
interface Teammate extends UserProfilePreview {
    role: TeamRole
    joined_at_millis: number
}

// ### GET:team
interface Team {
    team_id: string          // uuid
    team_name: string
    created_at_millis: number
    members: Teammate[]
}

// Scoreboard

interface Scoreboard {
    scoreboard_id: string    // uuid
    team_id: string          // uuid
    puzzle_date_iso_day: string   // which puzzle this scoreboard is for
    participants_qty: number
    score: Score[]          // the app will join the user preview from the team call
}

type ScoreboardPreview = Omit<Scoreboard, 'score'>

// ### GET:scoreboard
//     If start_dt_millis || end_dt_millis, only returns preview mode
//      request params:
//         - puzzle_date_iso_day: string
//         - team_id: string
//         - preview: boolean
//         - start_dt_millis?: number
//         - end_dt_millis?: number
//      request headers:
//         - page_size?: number // left blank will return max response
//     Response:
//         body: if preview=true, returns ScoreboardPreview, else Scoreboard
//         headers:
//         page_qty: string
//         pg_query_forward?: string
//         pg_query_backward?: string


// ## Internal data
interface GameDynamo {
    game_id: string          // uuid
    user_id: string          // uuid
    puzzle_id: string        // uuid
    puzzle_date_iso_day: string  // YYYY-MM-DD
    moves: GuessGraded[]     // 1-6 guesses
    moves_qty: number        // count of guesses
    completed_at_millis: number
    won: boolean
}

interface Puzzle {
    puzzle_id: string        // uuid even though cant we just use the date? Do we really need this?
    word: string
    date_iso_day: string     // date formatted like YYYY-MM-DD
}