// AGENTS: DO NOT EDIT THIS FILE WITHOUT EXPLICIT, EXTRA PERMISSION

// # Data Model

// ## API Requests

// Gameplay

// ### PUT:guess/

// Request Body: Game
interface Game {
    puzzle_date_iso_day: string;
    moves: string[];          // 1-6 items, each string is alphanumeric and 5 letters long
}


// Response Body: GameGraded
interface GuessLetterGraded {
    letter: string;           // string length == 1
    letter_contained_in_answer: boolean;
    correct_letter_and_position: boolean;
}
type GuessGraded = [
    GuessLetterGraded,
    GuessLetterGraded,
    GuessLetterGraded,
    GuessLetterGraded,
    GuessLetterGraded,
];

interface GameGraded {
    game_id: string;
    moves_qty: number;
    won: boolean;
    moves: [                 // 1-6 items
        GuessGraded,
        GuessGraded?,
        GuessGraded?,
        GuessGraded?,
        GuessGraded?,
        GuessGraded?,
    ];
}

// Profile
// ### GET:profile.          // a user's full profile

interface UserProfileBasics {
    user_id: string
    display_name: string
    name_pronunciation_url?: string
    pronouns?: string
    avatarUrl?: string
}

// Response Body: UserProfile
interface UserProfile extends UserProfileBasics {
    full_name?: string
    team_ids: string[]
    email: string
    city?: string
    state?: string
    country?: string
}

// Team

type TeamRole = 'admin' | 'member'

// ### PUT:team/teammate    // add a teammate
// ### DELETE:team/teammate // remove a teammate
// request body
interface TeamMembership {
    team_id: string
    user_id: string
    role: TeamRole
}

// request response: Teammate
interface Teammate extends UserProfileBasics {
    role: TeamRole
    joined_at_millis: number
}

interface Team {
    team_id: string          // uuid
    team_name: string
    created_at_millis: number
    members: Teammate[]
}

interface Scoreboard {
    scoreboard_id: string    // uuid
    team_id: string          // uuid
    puzzle_date_iso_day: string   // which puzzle this scoreboard is for
}

// ## Internal data
interface GameDynamo {
    game_id: string          // uuid
    user_id: string          // uuid
    puzzle_id: string        // uuid
    puzzle_date_iso_day: string  // YYYY-MM-DD
    moves: GuessGraded[]     // 1-6 guesses
    moves_qty: number        // count of guesses
    completed_at_millis: number
    won: boolean
}

interface Puzzle {
    puzzle_id: string        // uuid even though cant we just use the date? Do we really need this?
    word: string
    date_iso_day: string     // date formatted like YYYY-MM-DD
}